<?php

declare(strict_types=1);

return [
    ['OPTIONS', '/api/{any}', 'ApiHandler@options'],
    ['OPTIONS', '/api/{group}/{any}', 'ApiHandler@options'],
    ['GET', '/api/me', 'ApiHandler@me'],
    ['POST', '/api/login', 'ApiHandler@login'],
    ['POST', '/api/logout', 'ApiHandler@logout'],
    ['GET', '/api/dashboard', 'ApiHandler@dashboard'],
    ['GET', '/api/products', 'ApiHandler@products'],
    ['GET', '/api/stock', 'ApiHandler@stock'],
    ['GET', '/api/sales', 'ApiHandler@sales'],
    ['GET', '/api/purchases', 'ApiHandler@purchases'],
    ['GET', '/api/master', 'ApiHandler@master'],

    ['GET', '/', 'DashboardHandler@index'],
    ['GET', '/dashboard', 'DashboardHandler@index'],
    ['GET', '/dashboard/index', 'DashboardHandler@index'],

    ['GET', '/auth/login', 'AuthHandler@showLogin'],
    ['POST', '/auth/login', 'AuthHandler@login'],
    ['GET', '/auth/logout', 'AuthHandler@logout'],

    ['GET', '/product', 'ProductHandler@index'],
    ['GET', '/product/index', 'ProductHandler@index'],
    ['GET', '/product/create', 'ProductHandler@create'],
    ['POST', '/product/store', 'ProductHandler@store'],
    ['GET', '/product/edit/{id}', 'ProductHandler@edit'],
    ['POST', '/product/update/{id}', 'ProductHandler@update'],
    ['POST', '/product/delete/{id}', 'ProductHandler@delete'],

    ['GET', '/category', 'CategoryHandler@index'],
    ['GET', '/category/index', 'CategoryHandler@index'],
    ['GET', '/category/create', 'CategoryHandler@create'],
    ['POST', '/category/store', 'CategoryHandler@store'],
    ['GET', '/category/edit/{id}', 'CategoryHandler@edit'],
    ['POST', '/category/update/{id}', 'CategoryHandler@update'],
    ['POST', '/category/delete/{id}', 'CategoryHandler@delete'],

    ['GET', '/unit', 'UnitHandler@index'],
    ['GET', '/unit/index', 'UnitHandler@index'],
    ['GET', '/unit/create', 'UnitHandler@create'],
    ['POST', '/unit/store', 'UnitHandler@store'],
    ['GET', '/unit/edit/{id}', 'UnitHandler@edit'],
    ['POST', '/unit/update/{id}', 'UnitHandler@update'],
    ['POST', '/unit/delete/{id}', 'UnitHandler@delete'],

    ['GET', '/location', 'LocationHandler@index'],
    ['GET', '/location/index', 'LocationHandler@index'],
    ['GET', '/location/create', 'LocationHandler@create'],
    ['POST', '/location/store', 'LocationHandler@store'],
    ['GET', '/location/edit/{id}', 'LocationHandler@edit'],
    ['POST', '/location/update/{id}', 'LocationHandler@update'],
    ['POST', '/location/delete/{id}', 'LocationHandler@delete'],

    ['GET', '/supplier', 'SupplierHandler@index'],
    ['GET', '/supplier/index', 'SupplierHandler@index'],
    ['GET', '/supplier/create', 'SupplierHandler@create'],
    ['POST', '/supplier/store', 'SupplierHandler@store'],
    ['GET', '/supplier/edit/{id}', 'SupplierHandler@edit'],
    ['POST', '/supplier/update/{id}', 'SupplierHandler@update'],
    ['POST', '/supplier/delete/{id}', 'SupplierHandler@delete'],

    ['GET', '/customer', 'CustomerHandler@index'],
    ['GET', '/customer/index', 'CustomerHandler@index'],
    ['GET', '/customer/create', 'CustomerHandler@create'],
    ['POST', '/customer/store', 'CustomerHandler@store'],
    ['GET', '/customer/edit/{id}', 'CustomerHandler@edit'],
    ['POST', '/customer/update/{id}', 'CustomerHandler@update'],
    ['POST', '/customer/delete/{id}', 'CustomerHandler@delete'],

    ['GET', '/stock/overview', 'StockHandler@overview'],
    ['GET', '/stock/in', 'StockHandler@in'],
    ['POST', '/stock/process-in', 'StockHandler@processIn'],
    ['GET', '/stock/out', 'StockHandler@out'],
    ['POST', '/stock/process-out', 'StockHandler@processOut'],
    ['GET', '/stock/opname', 'StockHandler@opname'],
    ['POST', '/stock/process-opname', 'StockHandler@processOpname'],
    ['GET', '/stock/log', 'StockHandler@log'],

    ['GET', '/purchase', 'PurchaseHandler@index'],
    ['GET', '/purchase/index', 'PurchaseHandler@index'],
    ['GET', '/purchase/create', 'PurchaseHandler@create'],
    ['POST', '/purchase/store', 'PurchaseHandler@store'],
    ['GET', '/purchase/detail/{id}', 'PurchaseHandler@detail'],
    ['POST', '/purchase/receive/{id}', 'PurchaseHandler@receive'],

    ['GET', '/sales', 'SalesHandler@index'],
    ['GET', '/sales/index', 'SalesHandler@index'],
    ['GET', '/sales/create', 'SalesHandler@create'],
    ['POST', '/sales/store', 'SalesHandler@store'],
    ['GET', '/sales/detail/{id}', 'SalesHandler@detail'],
    ['POST', '/sales/pay/{id}', 'SalesHandler@addPayment'],
    ['GET', '/sales/print/{id}', 'SalesHandler@printInvoice'],
    ['POST', '/sales/cancel/{id}', 'SalesHandler@cancel'],

    ['GET', '/payment', 'PaymentHandler@index'],
    ['GET', '/payment/index', 'PaymentHandler@index'],

    ['GET', '/report/stock', 'ReportHandler@stock'],
    ['GET', '/report/sales', 'ReportHandler@sales'],
    ['GET', '/report/purchase', 'ReportHandler@purchase'],

    ['GET', '/setting', 'SettingHandler@index'],
    ['GET', '/setting/index', 'SettingHandler@index'],
    ['POST', '/setting/update', 'SettingHandler@update'],
];
